name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python -m unittest discover

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
      run: |
        echo "EC2_HOST=$EC2_HOST" >> .env
        echo "EC2_INSTANCE_ID=$EC2_INSTANCE_ID" >> .env
        chmod +x deploy_to_ec2.sh
        ./deploy_to_ec2.sh
    - name: Verify deployment
      run: |
        echo "Waiting for the server to start..."
        sleep 30
        if curl -s "http://${{ secrets.EC2_HOST }}:5001" | grep -q "Hello, World!"; then
          echo "Deployment successful!"
        else
          echo "Deployment verification failed"
          exit 1
        fi